<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Configurations\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Chinook.Data\Chinook.Data.csproj" />
  </ItemGroup>

</Project>
